In [5]:
import pandas as pd
import numpy as np 
import pickle
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score


In [6]:
df=pd.read_csv('IceCreamData.csv')


In [7]:
df.head()


Temperature     Revenue
0    24.566884  534.799028
1    26.005191  625.190122
2    27.790554  660.632289
3    20.595335  487.706960
4    11.503498  316.240194

In [8]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Temperature  500 non-null    float64
 1   Revenue      500 non-null    float64
dtypes: float64(2)
memory usage: 7.9 KB


In [9]:
X=df['Temperature']
y=df['Revenue']

In [10]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [12]:
len(X_train)


400

In [13]:
len(X_test)

100

In [14]:
model=LinearRegression()

In [15]:
y_test.ndim

1

In [16]:
y_train.ndim

1

In [17]:
np.array([X_train]).ndim

2

In [18]:
model.fit(np.array([X_train]).reshape(-1,1),y_train)

LinearRegression()

In [20]:
y_pred=model.predict(np.array(X_test).reshape(-1,1))

In [21]:
y_pred

array([457.51541735, 451.04538782, 376.5782991 , 584.87667409,
       462.16961732, 446.67399422, 718.88200369, 635.2332729 ,
       437.44322954, 523.93926857, 596.3800685 , 798.74239355,
       472.56754109, 455.8847962 , 410.38510537, 519.41986199,
       841.9716175 , 469.12267852, 393.35723819, 256.66879424,
       545.19141158, 572.75362803, 248.11562914, 900.82618008,
       545.9692313 , 280.46498789, 516.34578071, 606.42201722,
       393.40957545, 609.55360905, 555.44208813, 663.79456181,
       602.20716518, 507.55779658, 363.87705076, 898.77410133,
       379.92400874, 745.16586052, 313.04259917, 587.93527344,
       610.25784888, 750.77132471, 231.60895735, 655.96628886,
       183.17738065, 622.18801891, 759.85920943, 775.94267657,
       686.71575136, 546.44553579, 563.17530292, 529.47320693,
       546.52317404, 179.08357731, 447.45947425, 304.81221852,
       310.70385192, 958.03417364, 509.33558655, 588.94802731,
       407.4585229 , 661.09608916, 803.28857619, 493.18

In [22]:
y_test

449    452.626317
25     473.604335
289    350.629036
312    575.176896
471    429.435702
          ...    
79     682.752869
476    296.906532
198    608.936345
213    506.493748
96     474.749392
Name: Revenue, Length: 100, dtype: float64

In [23]:
r2_score(y_test,y_pred)

0.975681024529722

In [28]:
model.predict([(34.089,)])

array([776.53129413])

In [29]:
model.predict([(1,)])

array([63.79109466])

In [30]:
with open('model.pkl','wb') as files:
    pickle.dump(model,files)